#!/bin/sh

./runalarm -d -t 5 /bin/bash -c 'for i in $(seq 1 7); do echo $i; sleep 1; done; echo "exited"'
./runalarm -d -t 5 ./runstat -d -f foo /bin/bash -c 'for i in $(seq 1 7); do echo $i; sleep 1; done; echo "exited"'

(./runlock -d -f ../locks/foo bash -c 'for i in $(seq 1 5); do echo $i; sleep 1; done'; echo $?) & sleep 2 ; ./runlock -d -f ../locks/foo bash -c 'for i in $(seq 1 5); do echo $i; sleep 1; done'; echo exited $?
./runlock -d -f ../locks/foo bash -c 'for i in $(seq 1 5); do echo $i; sleep 1; done' & sleep 1; cat ../locks/foo
./runlock -d bash -c 'for i in $(seq 1 5); do echo $i; sleep 1; done'

./runstat -d -f foo bash -c 'for i in $(seq 1 5); do echo $i; done; exit 5'
./runstat -d -f foo ./runalarm -d -t 5 /bin/bash -c 'for i in $(seq 1 7); do echo $i; sleep 1; done; echo exited'; cat foo

./runstat -f foo usleep 4900000; cat foo
